// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        (unknown)
// source: inner/innerpb.proto

package inner

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{0}
}

type GateMsgWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GateSession string `protobuf:"bytes,1,opt,name=GateSession,json=gateSession,proto3" json:"GateSession"`
	MsgName     string `protobuf:"bytes,2,opt,name=MsgName,json=msgName,proto3" json:"MsgName"`
	Data        []byte `protobuf:"bytes,3,opt,name=Data,json=data,proto3" json:"Data"`
}

func (x *GateMsgWrapper) Reset() {
	*x = GateMsgWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateMsgWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateMsgWrapper) ProtoMessage() {}

func (x *GateMsgWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateMsgWrapper.ProtoReflect.Descriptor instead.
func (*GateMsgWrapper) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{1}
}

func (x *GateMsgWrapper) GetGateSession() string {
	if x != nil {
		return x.GateSession
	}
	return ""
}

func (x *GateMsgWrapper) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *GateMsgWrapper) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 存储信息
type G2DModelSave struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      []byte `protobuf:"bytes,1,opt,name=Data,json=data,proto3" json:"Data"`
	ModelName string `protobuf:"bytes,2,opt,name=ModelName,json=modelName,proto3" json:"ModelName"`
	RID       int64  `protobuf:"varint,3,opt,name=RID,json=rID,proto3" json:"RID"`
}

func (x *G2DModelSave) Reset() {
	*x = G2DModelSave{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2DModelSave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2DModelSave) ProtoMessage() {}

func (x *G2DModelSave) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2DModelSave.ProtoReflect.Descriptor instead.
func (*G2DModelSave) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{2}
}

func (x *G2DModelSave) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *G2DModelSave) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *G2DModelSave) GetRID() int64 {
	if x != nil {
		return x.RID
	}
	return 0
}

// login 请求所有角色数据
type L2DAllUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *L2DAllUserReq) Reset() {
	*x = L2DAllUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2DAllUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2DAllUserReq) ProtoMessage() {}

func (x *L2DAllUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2DAllUserReq.ProtoReflect.Descriptor instead.
func (*L2DAllUserReq) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{3}
}

type D2LAllUserRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=Data,json=data,proto3" json:"Data"` // models.GameUser
}

func (x *D2LAllUserRes) Reset() {
	*x = D2LAllUserRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *D2LAllUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*D2LAllUserRes) ProtoMessage() {}

func (x *D2LAllUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use D2LAllUserRes.ProtoReflect.Descriptor instead.
func (*D2LAllUserRes) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{4}
}

func (x *D2LAllUserRes) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// login 请求回存新玩家
type L2DUserSave struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=Data,json=data,proto3" json:"Data"` // models.GameUser
}

func (x *L2DUserSave) Reset() {
	*x = L2DUserSave{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2DUserSave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2DUserSave) ProtoMessage() {}

func (x *L2DUserSave) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2DUserSave.ProtoReflect.Descriptor instead.
func (*L2DUserSave) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{5}
}

func (x *L2DUserSave) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// game请求role数据
type G2DRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallbackId int64 `protobuf:"varint,1,opt,name=CallbackId,json=callbackId,proto3" json:"CallbackId"` // 回调Id
	RID        int64 `protobuf:"varint,2,opt,name=RID,json=rID,proto3" json:"RID"`
}

func (x *G2DRoleReq) Reset() {
	*x = G2DRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2DRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2DRoleReq) ProtoMessage() {}

func (x *G2DRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2DRoleReq.ProtoReflect.Descriptor instead.
func (*G2DRoleReq) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{6}
}

func (x *G2DRoleReq) GetCallbackId() int64 {
	if x != nil {
		return x.CallbackId
	}
	return 0
}

func (x *G2DRoleReq) GetRID() int64 {
	if x != nil {
		return x.RID
	}
	return 0
}

type D2GRoleRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallbackId int64             `protobuf:"varint,1,opt,name=CallbackId,json=callbackId,proto3" json:"CallbackId"` // 回调Id
	Valid      int32             `protobuf:"varint,2,opt,name=valid,proto3" json:"valid"`                           // 数据是否找到 0.成功 1.未找到角色
	RID        int64             `protobuf:"varint,3,opt,name=RID,json=rID,proto3" json:"RID"`
	WholeInfo  map[string][]byte `protobuf:"bytes,4,rep,name=WholeInfo,json=wholeInfo,proto3" json:"WholeInfo" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 角色各个模块的数据
}

func (x *D2GRoleRes) Reset() {
	*x = D2GRoleRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *D2GRoleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*D2GRoleRes) ProtoMessage() {}

func (x *D2GRoleRes) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use D2GRoleRes.ProtoReflect.Descriptor instead.
func (*D2GRoleRes) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{7}
}

func (x *D2GRoleRes) GetCallbackId() int64 {
	if x != nil {
		return x.CallbackId
	}
	return 0
}

func (x *D2GRoleRes) GetValid() int32 {
	if x != nil {
		return x.Valid
	}
	return 0
}

func (x *D2GRoleRes) GetRID() int64 {
	if x != nil {
		return x.RID
	}
	return 0
}

func (x *D2GRoleRes) GetWholeInfo() map[string][]byte {
	if x != nil {
		return x.WholeInfo
	}
	return nil
}

// gatesession断开,gate通知game
type GT2GSessionClosed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GateSession string `protobuf:"bytes,1,opt,name=GateSession,json=gateSession,proto3" json:"GateSession"` // 断开的session
}

func (x *GT2GSessionClosed) Reset() {
	*x = GT2GSessionClosed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GT2GSessionClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GT2GSessionClosed) ProtoMessage() {}

func (x *GT2GSessionClosed) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GT2GSessionClosed.ProtoReflect.Descriptor instead.
func (*GT2GSessionClosed) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{8}
}

func (x *GT2GSessionClosed) GetGateSession() string {
	if x != nil {
		return x.GateSession
	}
	return ""
}

// login通知gate 为session分配gameActor
type L2GTSessionAssignGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GateSession string `protobuf:"bytes,1,opt,name=GateSession,json=gateSession,proto3" json:"GateSession"` //
	GameActorId string `protobuf:"bytes,2,opt,name=GameActorId,json=gameActorId,proto3" json:"GameActorId"` // 分配的游戏Actor
}

func (x *L2GTSessionAssignGame) Reset() {
	*x = L2GTSessionAssignGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2GTSessionAssignGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2GTSessionAssignGame) ProtoMessage() {}

func (x *L2GTSessionAssignGame) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2GTSessionAssignGame.ProtoReflect.Descriptor instead.
func (*L2GTSessionAssignGame) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{9}
}

func (x *L2GTSessionAssignGame) GetGateSession() string {
	if x != nil {
		return x.GateSession
	}
	return ""
}

func (x *L2GTSessionAssignGame) GetGameActorId() string {
	if x != nil {
		return x.GameActorId
	}
	return ""
}

// game通知login，玩家离线
type G2LRoleOffline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID         int64  `protobuf:"varint,1,opt,name=UID,json=uID,proto3" json:"UID"`
	RID         int64  `protobuf:"varint,2,opt,name=RID,json=rID,proto3" json:"RID"`
	GateSession string `protobuf:"bytes,3,opt,name=GateSession,json=gateSession,proto3" json:"GateSession"` //
}

func (x *G2LRoleOffline) Reset() {
	*x = G2LRoleOffline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2LRoleOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2LRoleOffline) ProtoMessage() {}

func (x *G2LRoleOffline) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2LRoleOffline.ProtoReflect.Descriptor instead.
func (*G2LRoleOffline) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{10}
}

func (x *G2LRoleOffline) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *G2LRoleOffline) GetRID() int64 {
	if x != nil {
		return x.RID
	}
	return 0
}

func (x *G2LRoleOffline) GetGateSession() string {
	if x != nil {
		return x.GateSession
	}
	return ""
}

// game通知login，玩家离线
type G2DGameStop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *G2DGameStop) Reset() {
	*x = G2DGameStop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2DGameStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2DGameStop) ProtoMessage() {}

func (x *G2DGameStop) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2DGameStop.ProtoReflect.Descriptor instead.
func (*G2DGameStop) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{11}
}

// login通知game,玩家顶号，旧session失效
type L2GTUserSessionDisabled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GateSession string `protobuf:"bytes,1,opt,name=GateSession,json=gateSession,proto3" json:"GateSession"`
	UID         int64  `protobuf:"varint,2,opt,name=UID,json=uID,proto3" json:"UID"`
}

func (x *L2GTUserSessionDisabled) Reset() {
	*x = L2GTUserSessionDisabled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2GTUserSessionDisabled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2GTUserSessionDisabled) ProtoMessage() {}

func (x *L2GTUserSessionDisabled) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2GTUserSessionDisabled.ProtoReflect.Descriptor instead.
func (*L2GTUserSessionDisabled) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{12}
}

func (x *L2GTUserSessionDisabled) GetGateSession() string {
	if x != nil {
		return x.GateSession
	}
	return ""
}

func (x *L2GTUserSessionDisabled) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

//////////////////////////////////////////////////// world ///////////////////////////////////////////////////////////
// game通知world创建新玩家
type G2WCreateNewPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RID         int64   `protobuf:"varint,1,opt,name=RID,json=rID,proto3" json:"RID"`
	GateSession string  `protobuf:"bytes,2,opt,name=GateSession,json=gateSession,proto3" json:"GateSession"`
	EID         string  `protobuf:"bytes,3,opt,name=EID,json=eID,proto3" json:"EID"`
	X           float64 `protobuf:"fixed64,4,opt,name=X,json=x,proto3" json:"X"`
	Y           float64 `protobuf:"fixed64,5,opt,name=Y,json=y,proto3" json:"Y"`
}

func (x *G2WCreateNewPlayer) Reset() {
	*x = G2WCreateNewPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2WCreateNewPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2WCreateNewPlayer) ProtoMessage() {}

func (x *G2WCreateNewPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2WCreateNewPlayer.ProtoReflect.Descriptor instead.
func (*G2WCreateNewPlayer) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{13}
}

func (x *G2WCreateNewPlayer) GetRID() int64 {
	if x != nil {
		return x.RID
	}
	return 0
}

func (x *G2WCreateNewPlayer) GetGateSession() string {
	if x != nil {
		return x.GateSession
	}
	return ""
}

func (x *G2WCreateNewPlayer) GetEID() string {
	if x != nil {
		return x.EID
	}
	return ""
}

func (x *G2WCreateNewPlayer) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *G2WCreateNewPlayer) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

// game通知world玩家进入世界
type G2WEnterPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RID         int64  `protobuf:"varint,1,opt,name=RID,json=rID,proto3" json:"RID"`
	GateSession string `protobuf:"bytes,2,opt,name=GateSession,json=gateSession,proto3" json:"GateSession"`
	EID         string `protobuf:"bytes,3,opt,name=EID,json=eID,proto3" json:"EID"`
}

func (x *G2WEnterPlayer) Reset() {
	*x = G2WEnterPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2WEnterPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2WEnterPlayer) ProtoMessage() {}

func (x *G2WEnterPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2WEnterPlayer.ProtoReflect.Descriptor instead.
func (*G2WEnterPlayer) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{14}
}

func (x *G2WEnterPlayer) GetRID() int64 {
	if x != nil {
		return x.RID
	}
	return 0
}

func (x *G2WEnterPlayer) GetGateSession() string {
	if x != nil {
		return x.GateSession
	}
	return ""
}

func (x *G2WEnterPlayer) GetEID() string {
	if x != nil {
		return x.EID
	}
	return ""
}

// game通知world session断开
type G2WInvaildSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GateSession string `protobuf:"bytes,1,opt,name=GateSession,json=gateSession,proto3" json:"GateSession"`
}

func (x *G2WInvaildSession) Reset() {
	*x = G2WInvaildSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2WInvaildSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2WInvaildSession) ProtoMessage() {}

func (x *G2WInvaildSession) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2WInvaildSession.ProtoReflect.Descriptor instead.
func (*G2WInvaildSession) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{15}
}

func (x *G2WInvaildSession) GetGateSession() string {
	if x != nil {
		return x.GateSession
	}
	return ""
}

//////////////////////////////////////////////////// cross area ///////////////////////////////////////////////////////
// 实体信息
type EntityInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EId  string            `protobuf:"bytes,1,opt,name=EId,json=eId,proto3" json:"EId"`
	Data map[uint64][]byte `protobuf:"bytes,2,rep,name=Data,json=data,proto3" json:"Data" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *EntityInfo) Reset() {
	*x = EntityInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityInfo) ProtoMessage() {}

func (x *EntityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityInfo.ProtoReflect.Descriptor instead.
func (*EntityInfo) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{16}
}

func (x *EntityInfo) GetEId() string {
	if x != nil {
		return x.EId
	}
	return ""
}

func (x *EntityInfo) GetData() map[uint64][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 通知邻近区域，添加实体
type W2WAddDuplicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity *EntityInfo `protobuf:"bytes,1,opt,name=Entity,json=entity,proto3" json:"Entity"`
}

func (x *W2WAddDuplicate) Reset() {
	*x = W2WAddDuplicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *W2WAddDuplicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*W2WAddDuplicate) ProtoMessage() {}

func (x *W2WAddDuplicate) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use W2WAddDuplicate.ProtoReflect.Descriptor instead.
func (*W2WAddDuplicate) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{17}
}

func (x *W2WAddDuplicate) GetEntity() *EntityInfo {
	if x != nil {
		return x.Entity
	}
	return nil
}

// 通知邻近区域，删除实体
type W2WDelDuplicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EId string `protobuf:"bytes,1,opt,name=EId,json=eId,proto3" json:"EId"`
}

func (x *W2WDelDuplicate) Reset() {
	*x = W2WDelDuplicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *W2WDelDuplicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*W2WDelDuplicate) ProtoMessage() {}

func (x *W2WDelDuplicate) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use W2WDelDuplicate.ProtoReflect.Descriptor instead.
func (*W2WDelDuplicate) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{18}
}

func (x *W2WDelDuplicate) GetEId() string {
	if x != nil {
		return x.EId
	}
	return ""
}

// 通知邻近区域，更新实体
type W2WUpdateDuplicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity *EntityInfo `protobuf:"bytes,1,opt,name=Entity,json=entity,proto3" json:"Entity"`
}

func (x *W2WUpdateDuplicate) Reset() {
	*x = W2WUpdateDuplicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *W2WUpdateDuplicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*W2WUpdateDuplicate) ProtoMessage() {}

func (x *W2WUpdateDuplicate) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use W2WUpdateDuplicate.ProtoReflect.Descriptor instead.
func (*W2WUpdateDuplicate) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{19}
}

func (x *W2WUpdateDuplicate) GetEntity() *EntityInfo {
	if x != nil {
		return x.Entity
	}
	return nil
}

// 通知centerworld 更新实体所在区域
type W2CenterUpdateEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EId    string `protobuf:"bytes,1,opt,name=EId,json=eId,proto3" json:"EId"`
	AreaId int32  `protobuf:"varint,2,opt,name=AreaId,json=areaId,proto3" json:"AreaId"` // 区域号
}

func (x *W2CenterUpdateEntity) Reset() {
	*x = W2CenterUpdateEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *W2CenterUpdateEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*W2CenterUpdateEntity) ProtoMessage() {}

func (x *W2CenterUpdateEntity) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use W2CenterUpdateEntity.ProtoReflect.Descriptor instead.
func (*W2CenterUpdateEntity) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{20}
}

func (x *W2CenterUpdateEntity) GetEId() string {
	if x != nil {
		return x.EId
	}
	return ""
}

func (x *W2CenterUpdateEntity) GetAreaId() int32 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

//world通知center删除
type W2CenterDeleteEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EId string `protobuf:"bytes,1,opt,name=EId,json=eId,proto3" json:"EId"`
}

func (x *W2CenterDeleteEntity) Reset() {
	*x = W2CenterDeleteEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *W2CenterDeleteEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*W2CenterDeleteEntity) ProtoMessage() {}

func (x *W2CenterDeleteEntity) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use W2CenterDeleteEntity.ProtoReflect.Descriptor instead.
func (*W2CenterDeleteEntity) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{21}
}

func (x *W2CenterDeleteEntity) GetEId() string {
	if x != nil {
		return x.EId
	}
	return ""
}

//////////////////////////////////////////////////////////////Fight//////////////////////////////////////////////////////
// 战斗属性
type FightAttr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sets map[int32]int64 `protobuf:"bytes,1,rep,name=Sets,json=sets,proto3" json:"Sets" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *FightAttr) Reset() {
	*x = FightAttr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FightAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FightAttr) ProtoMessage() {}

func (x *FightAttr) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FightAttr.ProtoReflect.Descriptor instead.
func (*FightAttr) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{22}
}

func (x *FightAttr) GetSets() map[int32]int64 {
	if x != nil {
		return x.Sets
	}
	return nil
}

// 发起攻击
type W2WAttackReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttackerEId  string     `protobuf:"bytes,1,opt,name=AttackerEId,json=attackerEId,proto3" json:"AttackerEId"`    // 攻击者
	DefenderEId  string     `protobuf:"bytes,2,opt,name=DefenderEId,json=defenderEId,proto3" json:"DefenderEId"`    // 防御者
	TurnNumber   int32      `protobuf:"varint,3,opt,name=TurnNumber,json=turnNumber,proto3" json:"TurnNumber"`      // 攻击者的回合号
	AttackerAttr *FightAttr `protobuf:"bytes,4,opt,name=AttackerAttr,json=attackerAttr,proto3" json:"AttackerAttr"` // 攻击者本回合属性
}

func (x *W2WAttackReq) Reset() {
	*x = W2WAttackReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *W2WAttackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*W2WAttackReq) ProtoMessage() {}

func (x *W2WAttackReq) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use W2WAttackReq.ProtoReflect.Descriptor instead.
func (*W2WAttackReq) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{23}
}

func (x *W2WAttackReq) GetAttackerEId() string {
	if x != nil {
		return x.AttackerEId
	}
	return ""
}

func (x *W2WAttackReq) GetDefenderEId() string {
	if x != nil {
		return x.DefenderEId
	}
	return ""
}

func (x *W2WAttackReq) GetTurnNumber() int32 {
	if x != nil {
		return x.TurnNumber
	}
	return 0
}

func (x *W2WAttackReq) GetAttackerAttr() *FightAttr {
	if x != nil {
		return x.AttackerAttr
	}
	return nil
}

type W2WAttackResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttackerEId string `protobuf:"bytes,1,opt,name=AttackerEId,json=attackerEId,proto3" json:"AttackerEId"` // 攻击者
	DefenderEId string `protobuf:"bytes,2,opt,name=DefenderEId,json=defenderEId,proto3" json:"DefenderEId"` // 防御者
	TurnNumber  int32  `protobuf:"varint,3,opt,name=TurnNumber,json=turnNumber,proto3" json:"TurnNumber"`   // 攻击者的回合计数
	DamageVal   int64  `protobuf:"varint,4,opt,name=DamageVal,json=damageVal,proto3" json:"DamageVal"`      // 攻击伤害
	CounterVal  int64  `protobuf:"varint,5,opt,name=CounterVal,json=counterVal,proto3" json:"CounterVal"`   // 反击伤害
}

func (x *W2WAttackResp) Reset() {
	*x = W2WAttackResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *W2WAttackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*W2WAttackResp) ProtoMessage() {}

func (x *W2WAttackResp) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use W2WAttackResp.ProtoReflect.Descriptor instead.
func (*W2WAttackResp) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{24}
}

func (x *W2WAttackResp) GetAttackerEId() string {
	if x != nil {
		return x.AttackerEId
	}
	return ""
}

func (x *W2WAttackResp) GetDefenderEId() string {
	if x != nil {
		return x.DefenderEId
	}
	return ""
}

func (x *W2WAttackResp) GetTurnNumber() int32 {
	if x != nil {
		return x.TurnNumber
	}
	return 0
}

func (x *W2WAttackResp) GetDamageVal() int64 {
	if x != nil {
		return x.DamageVal
	}
	return 0
}

func (x *W2WAttackResp) GetCounterVal() int64 {
	if x != nil {
		return x.CounterVal
	}
	return 0
}

//////////////////////////////////////////////////////////////UI//////////////////////////////////////////////////////
type Bound struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos    *Vec3F  `protobuf:"bytes,1,opt,name=Pos,json=pos,proto3" json:"Pos"`
	Width  float64 `protobuf:"fixed64,2,opt,name=Width,json=width,proto3" json:"Width"`
	Height float64 `protobuf:"fixed64,3,opt,name=Height,json=height,proto3" json:"Height"`
}

func (x *Bound) Reset() {
	*x = Bound{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bound) ProtoMessage() {}

func (x *Bound) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bound.ProtoReflect.Descriptor instead.
func (*Bound) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{25}
}

func (x *Bound) GetPos() *Vec3F {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Bound) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Bound) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Vec3F struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=X,json=x,proto3" json:"X"`
	Y float64 `protobuf:"fixed64,2,opt,name=Y,json=y,proto3" json:"Y"`
	Z float64 `protobuf:"fixed64,3,opt,name=Z,json=z,proto3" json:"Z"`
}

func (x *Vec3F) Reset() {
	*x = Vec3F{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vec3F) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec3F) ProtoMessage() {}

func (x *Vec3F) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec3F.ProtoReflect.Descriptor instead.
func (*Vec3F) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{26}
}

func (x *Vec3F) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec3F) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vec3F) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

// 添加新实体
type U2GAddEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EID     string `protobuf:"bytes,1,opt,name=EID,json=eID,proto3" json:"EID"`
	RealPos *Vec3F `protobuf:"bytes,2,opt,name=RealPos,json=realPos,proto3" json:"RealPos"`
	AreaNum int32  `protobuf:"varint,3,opt,name=areaNum,proto3" json:"areaNum"`
}

func (x *U2GAddEntity) Reset() {
	*x = U2GAddEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *U2GAddEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*U2GAddEntity) ProtoMessage() {}

func (x *U2GAddEntity) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use U2GAddEntity.ProtoReflect.Descriptor instead.
func (*U2GAddEntity) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{27}
}

func (x *U2GAddEntity) GetEID() string {
	if x != nil {
		return x.EID
	}
	return ""
}

func (x *U2GAddEntity) GetRealPos() *Vec3F {
	if x != nil {
		return x.RealPos
	}
	return nil
}

func (x *U2GAddEntity) GetAreaNum() int32 {
	if x != nil {
		return x.AreaNum
	}
	return 0
}

// 添加新实体
type G2UAddEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EID       string `protobuf:"bytes,1,opt,name=EID,json=eID,proto3" json:"EID"`
	RealPos   *Vec3F `protobuf:"bytes,2,opt,name=RealPos,json=realPos,proto3" json:"RealPos"`
	Duplicate bool   `protobuf:"varint,3,opt,name=Duplicate,json=duplicate,proto3" json:"Duplicate"`
	AreaNum   int32  `protobuf:"varint,4,opt,name=areaNum,proto3" json:"areaNum"`
}

func (x *G2UAddEntity) Reset() {
	*x = G2UAddEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2UAddEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2UAddEntity) ProtoMessage() {}

func (x *G2UAddEntity) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2UAddEntity.ProtoReflect.Descriptor instead.
func (*G2UAddEntity) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{28}
}

func (x *G2UAddEntity) GetEID() string {
	if x != nil {
		return x.EID
	}
	return ""
}

func (x *G2UAddEntity) GetRealPos() *Vec3F {
	if x != nil {
		return x.RealPos
	}
	return nil
}

func (x *G2UAddEntity) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

func (x *G2UAddEntity) GetAreaNum() int32 {
	if x != nil {
		return x.AreaNum
	}
	return 0
}

// 删除实体
type U2GDelEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EID     string `protobuf:"bytes,1,opt,name=EID,json=eID,proto3" json:"EID"`
	AreaNum int32  `protobuf:"varint,2,opt,name=areaNum,proto3" json:"areaNum"`
}

func (x *U2GDelEntity) Reset() {
	*x = U2GDelEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *U2GDelEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*U2GDelEntity) ProtoMessage() {}

func (x *U2GDelEntity) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use U2GDelEntity.ProtoReflect.Descriptor instead.
func (*U2GDelEntity) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{29}
}

func (x *U2GDelEntity) GetEID() string {
	if x != nil {
		return x.EID
	}
	return ""
}

func (x *U2GDelEntity) GetAreaNum() int32 {
	if x != nil {
		return x.AreaNum
	}
	return 0
}

// 删除实体
type G2UDelEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EID       string `protobuf:"bytes,1,opt,name=EID,json=eID,proto3" json:"EID"`
	Duplicate bool   `protobuf:"varint,2,opt,name=Duplicate,json=duplicate,proto3" json:"Duplicate"`
	AreaId    int32  `protobuf:"varint,3,opt,name=areaId,proto3" json:"areaId"`
}

func (x *G2UDelEntity) Reset() {
	*x = G2UDelEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2UDelEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2UDelEntity) ProtoMessage() {}

func (x *G2UDelEntity) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2UDelEntity.ProtoReflect.Descriptor instead.
func (*G2UDelEntity) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{30}
}

func (x *G2UDelEntity) GetEID() string {
	if x != nil {
		return x.EID
	}
	return ""
}

func (x *G2UDelEntity) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

func (x *G2UDelEntity) GetAreaId() int32 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

// 实体移动
type G2UUpdateEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EID       string `protobuf:"bytes,1,opt,name=EID,json=eID,proto3" json:"EID"`
	RealPos   *Vec3F `protobuf:"bytes,2,opt,name=RealPos,json=realPos,proto3" json:"RealPos"`
	AreaId    int32  `protobuf:"varint,3,opt,name=areaId,proto3" json:"areaId"`
	Hp        int64  `protobuf:"varint,4,opt,name=Hp,json=hp,proto3" json:"Hp"`
	Duplicate bool   `protobuf:"varint,5,opt,name=Duplicate,json=duplicate,proto3" json:"Duplicate"`
}

func (x *G2UUpdateEntity) Reset() {
	*x = G2UUpdateEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2UUpdateEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2UUpdateEntity) ProtoMessage() {}

func (x *G2UUpdateEntity) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2UUpdateEntity.ProtoReflect.Descriptor instead.
func (*G2UUpdateEntity) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{31}
}

func (x *G2UUpdateEntity) GetEID() string {
	if x != nil {
		return x.EID
	}
	return ""
}

func (x *G2UUpdateEntity) GetRealPos() *Vec3F {
	if x != nil {
		return x.RealPos
	}
	return nil
}

func (x *G2UUpdateEntity) GetAreaId() int32 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

func (x *G2UUpdateEntity) GetHp() int64 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *G2UUpdateEntity) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

// UI请求实体移动
type U2GMoveEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EID   string   `protobuf:"bytes,1,opt,name=EID,json=eID,proto3" json:"EID"`
	Speed float64  `protobuf:"fixed64,2,opt,name=Speed,json=speed,proto3" json:"Speed"`
	Path  []*Vec3F `protobuf:"bytes,3,rep,name=Path,json=path,proto3" json:"Path"`
}

func (x *U2GMoveEntity) Reset() {
	*x = U2GMoveEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *U2GMoveEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*U2GMoveEntity) ProtoMessage() {}

func (x *U2GMoveEntity) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use U2GMoveEntity.ProtoReflect.Descriptor instead.
func (*U2GMoveEntity) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{32}
}

func (x *U2GMoveEntity) GetEID() string {
	if x != nil {
		return x.EID
	}
	return ""
}

func (x *U2GMoveEntity) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *U2GMoveEntity) GetPath() []*Vec3F {
	if x != nil {
		return x.Path
	}
	return nil
}

// world通知UI地图区域
type G2UArea struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorldId        int64    `protobuf:"varint,1,opt,name=WorldId,json=worldId,proto3" json:"WorldId"`
	ExclusiveBound *Bound   `protobuf:"bytes,2,opt,name=ExclusiveBound,json=exclusiveBound,proto3" json:"ExclusiveBound"`
	ActualBound    *Bound   `protobuf:"bytes,3,opt,name=ActualBound,json=actualBound,proto3" json:"ActualBound"`
	Point          []*Vec3F `protobuf:"bytes,4,rep,name=Point,json=point,proto3" json:"Point"`
}

func (x *G2UArea) Reset() {
	*x = G2UArea{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2UArea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2UArea) ProtoMessage() {}

func (x *G2UArea) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2UArea.ProtoReflect.Descriptor instead.
func (*G2UArea) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{33}
}

func (x *G2UArea) GetWorldId() int64 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *G2UArea) GetExclusiveBound() *Bound {
	if x != nil {
		return x.ExclusiveBound
	}
	return nil
}

func (x *G2UArea) GetActualBound() *Bound {
	if x != nil {
		return x.ActualBound
	}
	return nil
}

func (x *G2UArea) GetPoint() []*Vec3F {
	if x != nil {
		return x.Point
	}
	return nil
}

// 通知UI更新当前帧实体数量
type G2UCountEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorldId int64 `protobuf:"varint,1,opt,name=WorldId,json=worldId,proto3" json:"WorldId"`
	Count   int32 `protobuf:"varint,2,opt,name=Count,json=count,proto3" json:"Count"`
}

func (x *G2UCountEntity) Reset() {
	*x = G2UCountEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_innerpb_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2UCountEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2UCountEntity) ProtoMessage() {}

func (x *G2UCountEntity) ProtoReflect() protoreflect.Message {
	mi := &file_inner_innerpb_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2UCountEntity.ProtoReflect.Descriptor instead.
func (*G2UCountEntity) Descriptor() ([]byte, []int) {
	return file_inner_innerpb_proto_rawDescGZIP(), []int{34}
}

func (x *G2UCountEntity) GetWorldId() int64 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *G2UCountEntity) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_inner_innerpb_proto protoreflect.FileDescriptor

var file_inner_innerpb_proto_rawDesc = []byte{
	0x0a, 0x13, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x62, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x60, 0x0a,
	0x0e, 0x47, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12,
	0x20, 0x0a, 0x0b, 0x47, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x52, 0x0a, 0x0c, 0x47, 0x32, 0x44, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x61, 0x76, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x72, 0x49, 0x44, 0x22, 0x0f, 0x0a, 0x0d, 0x4c, 0x32, 0x44, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x22, 0x23, 0x0a, 0x0d, 0x44, 0x32, 0x4c, 0x41, 0x6c, 0x6c, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x21, 0x0a, 0x0b, 0x4c, 0x32, 0x44,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x61, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3e, 0x0a, 0x0a,
	0x47, 0x32, 0x44, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x61,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x49, 0x44, 0x22, 0xda, 0x01, 0x0a,
	0x0a, 0x44, 0x32, 0x47, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x43,
	0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x72, 0x49, 0x44, 0x12, 0x46, 0x0a, 0x09, 0x57, 0x68, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x32, 0x47, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x2e, 0x57, 0x68, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x09, 0x77, 0x68, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x3c, 0x0a, 0x0e, 0x57,
	0x68, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x35, 0x0a, 0x11, 0x47, 0x54, 0x32,
	0x47, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x47, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x5b, 0x0a, 0x15, 0x4c, 0x32, 0x47, 0x54, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x47, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x47,
	0x61, 0x6d, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x56, 0x0a,
	0x0e, 0x47, 0x32, 0x4c, 0x52, 0x6f, 0x6c, 0x65, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x49,
	0x44, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x72, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x47, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x0d, 0x0a, 0x0b, 0x47, 0x32, 0x44, 0x47, 0x61, 0x6d, 0x65,
	0x53, 0x74, 0x6f, 0x70, 0x22, 0x4d, 0x0a, 0x17, 0x4c, 0x32, 0x47, 0x54, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x47, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x75, 0x49, 0x44, 0x22, 0x76, 0x0a, 0x12, 0x47, 0x32, 0x57, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4e, 0x65, 0x77, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x47,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x45, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x49, 0x44, 0x12,
	0x0c, 0x0a, 0x01, 0x58, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a,
	0x01, 0x59, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x22, 0x56, 0x0a, 0x0e, 0x47,
	0x32, 0x57, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x10, 0x0a,
	0x03, 0x52, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x49, 0x44, 0x12,
	0x20, 0x0a, 0x0b, 0x47, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x65, 0x49, 0x44, 0x22, 0x35, 0x0a, 0x11, 0x47, 0x32, 0x57, 0x49, 0x6e, 0x76, 0x61, 0x69, 0x6c,
	0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x47, 0x61, 0x74, 0x65,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x90, 0x01, 0x0a, 0x0a, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x69, 0x6e, 0x6e, 0x65,
	0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x1a, 0x37, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x44, 0x0a,
	0x0f, 0x57, 0x32, 0x57, 0x41, 0x64, 0x64, 0x44, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x12, 0x31, 0x0a, 0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x22, 0x23, 0x0a, 0x0f, 0x57, 0x32, 0x57, 0x44, 0x65, 0x6c, 0x44, 0x75, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x12, 0x57, 0x32, 0x57, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x31,
	0x0a, 0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x22, 0x40, 0x0a, 0x14, 0x57, 0x32, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x41,
	0x72, 0x65, 0x61, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x72, 0x65,
	0x61, 0x49, 0x64, 0x22, 0x28, 0x0a, 0x14, 0x57, 0x32, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x45,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x49, 0x64, 0x22, 0x7c, 0x0a,
	0x09, 0x46, 0x69, 0x67, 0x68, 0x74, 0x41, 0x74, 0x74, 0x72, 0x12, 0x36, 0x0a, 0x04, 0x53, 0x65,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x69, 0x67, 0x68, 0x74, 0x41, 0x74,
	0x74, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x73, 0x65,
	0x74, 0x73, 0x1a, 0x37, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xb0, 0x01, 0x0a, 0x0c,
	0x57, 0x32, 0x57, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x45, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x45, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x44, 0x65, 0x66, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x45, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x66, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x45, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x75, 0x72, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x75, 0x72, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x3c, 0x0a, 0x0c, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x41, 0x74, 0x74, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x69, 0x67, 0x68, 0x74, 0x41, 0x74, 0x74, 0x72,
	0x52, 0x0c, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x41, 0x74, 0x74, 0x72, 0x22, 0xb1,
	0x01, 0x0a, 0x0d, 0x57, 0x32, 0x57, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x20, 0x0a, 0x0b, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x45, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x45,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x66, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x45, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x66, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x45, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x75, 0x72, 0x6e, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x75, 0x72, 0x6e, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x56, 0x61,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x56,
	0x61, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x56, 0x61, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x56,
	0x61, 0x6c, 0x22, 0x5d, 0x0a, 0x05, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x26, 0x0a, 0x03, 0x50,
	0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x46, 0x52, 0x03,
	0x70, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x22, 0x31, 0x0a, 0x05, 0x56, 0x65, 0x63, 0x33, 0x46, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x59, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x5a, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x01, 0x7a, 0x22, 0x6a, 0x0a, 0x0c, 0x55, 0x32, 0x47, 0x41, 0x64, 0x64, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x65, 0x49, 0x44, 0x12, 0x2e, 0x0a, 0x07, 0x52, 0x65, 0x61, 0x6c, 0x50, 0x6f,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x46, 0x52, 0x07, 0x72,
	0x65, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x72, 0x65, 0x61, 0x4e, 0x75,
	0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x72, 0x65, 0x61, 0x4e, 0x75, 0x6d,
	0x22, 0x88, 0x01, 0x0a, 0x0c, 0x47, 0x32, 0x55, 0x41, 0x64, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x65, 0x49, 0x44, 0x12, 0x2e, 0x0a, 0x07, 0x52, 0x65, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x46, 0x52, 0x07, 0x72, 0x65, 0x61, 0x6c,
	0x50, 0x6f, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x64, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x72, 0x65, 0x61, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x61, 0x72, 0x65, 0x61, 0x4e, 0x75, 0x6d, 0x22, 0x3a, 0x0a, 0x0c, 0x55,
	0x32, 0x47, 0x44, 0x65, 0x6c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x45,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x49, 0x44, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x72, 0x65, 0x61, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x61, 0x72, 0x65, 0x61, 0x4e, 0x75, 0x6d, 0x22, 0x56, 0x0a, 0x0c, 0x47, 0x32, 0x55, 0x44, 0x65,
	0x6c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x75, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x64, 0x75,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x65, 0x61, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x72, 0x65, 0x61, 0x49, 0x64, 0x22,
	0x99, 0x01, 0x0a, 0x0f, 0x47, 0x32, 0x55, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x65, 0x49, 0x44, 0x12, 0x2e, 0x0a, 0x07, 0x52, 0x65, 0x61, 0x6c, 0x50, 0x6f, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x46, 0x52, 0x07, 0x72, 0x65,
	0x61, 0x6c, 0x50, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x65, 0x61, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x72, 0x65, 0x61, 0x49, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x48, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x68, 0x70, 0x12, 0x1c, 0x0a,
	0x09, 0x44, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x64, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x22, 0x61, 0x0a, 0x0d, 0x55,
	0x32, 0x47, 0x4d, 0x6f, 0x76, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x45, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x49, 0x44, 0x12, 0x14,
	0x0a, 0x05, 0x53, 0x70, 0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73,
	0x70, 0x65, 0x65, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x46, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0xc5,
	0x01, 0x0a, 0x07, 0x47, 0x32, 0x55, 0x41, 0x72, 0x65, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x57, 0x6f,
	0x72, 0x6c, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x0e, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76,
	0x65, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69,
	0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x6f, 0x75,
	0x6e, 0x64, 0x52, 0x0e, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x42, 0x6f, 0x75,
	0x6e, 0x64, 0x12, 0x36, 0x0a, 0x0b, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x42, 0x6f, 0x75, 0x6e,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x0b, 0x61,
	0x63, 0x74, 0x75, 0x61, 0x6c, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x6e, 0x6e, 0x65,
	0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x46, 0x52,
	0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x40, 0x0a, 0x0e, 0x47, 0x32, 0x55, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x57, 0x6f, 0x72, 0x6c,
	0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x69, 0x6e, 0x6e,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inner_innerpb_proto_rawDescOnce sync.Once
	file_inner_innerpb_proto_rawDescData = file_inner_innerpb_proto_rawDesc
)

func file_inner_innerpb_proto_rawDescGZIP() []byte {
	file_inner_innerpb_proto_rawDescOnce.Do(func() {
		file_inner_innerpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_inner_innerpb_proto_rawDescData)
	})
	return file_inner_innerpb_proto_rawDescData
}

var file_inner_innerpb_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_inner_innerpb_proto_goTypes = []interface{}{
	(*Error)(nil),                   // 0: inner_message.Error
	(*GateMsgWrapper)(nil),          // 1: inner_message.GateMsgWrapper
	(*G2DModelSave)(nil),            // 2: inner_message.G2DModelSave
	(*L2DAllUserReq)(nil),           // 3: inner_message.L2DAllUserReq
	(*D2LAllUserRes)(nil),           // 4: inner_message.D2LAllUserRes
	(*L2DUserSave)(nil),             // 5: inner_message.L2DUserSave
	(*G2DRoleReq)(nil),              // 6: inner_message.G2DRoleReq
	(*D2GRoleRes)(nil),              // 7: inner_message.D2GRoleRes
	(*GT2GSessionClosed)(nil),       // 8: inner_message.GT2GSessionClosed
	(*L2GTSessionAssignGame)(nil),   // 9: inner_message.L2GTSessionAssignGame
	(*G2LRoleOffline)(nil),          // 10: inner_message.G2LRoleOffline
	(*G2DGameStop)(nil),             // 11: inner_message.G2DGameStop
	(*L2GTUserSessionDisabled)(nil), // 12: inner_message.L2GTUserSessionDisabled
	(*G2WCreateNewPlayer)(nil),      // 13: inner_message.G2WCreateNewPlayer
	(*G2WEnterPlayer)(nil),          // 14: inner_message.G2WEnterPlayer
	(*G2WInvaildSession)(nil),       // 15: inner_message.G2WInvaildSession
	(*EntityInfo)(nil),              // 16: inner_message.EntityInfo
	(*W2WAddDuplicate)(nil),         // 17: inner_message.W2WAddDuplicate
	(*W2WDelDuplicate)(nil),         // 18: inner_message.W2WDelDuplicate
	(*W2WUpdateDuplicate)(nil),      // 19: inner_message.W2WUpdateDuplicate
	(*W2CenterUpdateEntity)(nil),    // 20: inner_message.W2CenterUpdateEntity
	(*W2CenterDeleteEntity)(nil),    // 21: inner_message.W2CenterDeleteEntity
	(*FightAttr)(nil),               // 22: inner_message.FightAttr
	(*W2WAttackReq)(nil),            // 23: inner_message.W2WAttackReq
	(*W2WAttackResp)(nil),           // 24: inner_message.W2WAttackResp
	(*Bound)(nil),                   // 25: inner_message.Bound
	(*Vec3F)(nil),                   // 26: inner_message.Vec3F
	(*U2GAddEntity)(nil),            // 27: inner_message.U2GAddEntity
	(*G2UAddEntity)(nil),            // 28: inner_message.G2UAddEntity
	(*U2GDelEntity)(nil),            // 29: inner_message.U2GDelEntity
	(*G2UDelEntity)(nil),            // 30: inner_message.G2UDelEntity
	(*G2UUpdateEntity)(nil),         // 31: inner_message.G2UUpdateEntity
	(*U2GMoveEntity)(nil),           // 32: inner_message.U2GMoveEntity
	(*G2UArea)(nil),                 // 33: inner_message.G2UArea
	(*G2UCountEntity)(nil),          // 34: inner_message.G2UCountEntity
	nil,                             // 35: inner_message.D2GRoleRes.WholeInfoEntry
	nil,                             // 36: inner_message.EntityInfo.DataEntry
	nil,                             // 37: inner_message.FightAttr.SetsEntry
}
var file_inner_innerpb_proto_depIdxs = []int32{
	35, // 0: inner_message.D2GRoleRes.WholeInfo:type_name -> inner_message.D2GRoleRes.WholeInfoEntry
	36, // 1: inner_message.EntityInfo.Data:type_name -> inner_message.EntityInfo.DataEntry
	16, // 2: inner_message.W2WAddDuplicate.Entity:type_name -> inner_message.EntityInfo
	16, // 3: inner_message.W2WUpdateDuplicate.Entity:type_name -> inner_message.EntityInfo
	37, // 4: inner_message.FightAttr.Sets:type_name -> inner_message.FightAttr.SetsEntry
	22, // 5: inner_message.W2WAttackReq.AttackerAttr:type_name -> inner_message.FightAttr
	26, // 6: inner_message.Bound.Pos:type_name -> inner_message.Vec3F
	26, // 7: inner_message.U2GAddEntity.RealPos:type_name -> inner_message.Vec3F
	26, // 8: inner_message.G2UAddEntity.RealPos:type_name -> inner_message.Vec3F
	26, // 9: inner_message.G2UUpdateEntity.RealPos:type_name -> inner_message.Vec3F
	26, // 10: inner_message.U2GMoveEntity.Path:type_name -> inner_message.Vec3F
	25, // 11: inner_message.G2UArea.ExclusiveBound:type_name -> inner_message.Bound
	25, // 12: inner_message.G2UArea.ActualBound:type_name -> inner_message.Bound
	26, // 13: inner_message.G2UArea.Point:type_name -> inner_message.Vec3F
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_inner_innerpb_proto_init() }
func file_inner_innerpb_proto_init() {
	if File_inner_innerpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inner_innerpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateMsgWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2DModelSave); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2DAllUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*D2LAllUserRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2DUserSave); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2DRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*D2GRoleRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GT2GSessionClosed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2GTSessionAssignGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2LRoleOffline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2DGameStop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2GTUserSessionDisabled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2WCreateNewPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2WEnterPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2WInvaildSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*W2WAddDuplicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*W2WDelDuplicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*W2WUpdateDuplicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*W2CenterUpdateEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*W2CenterDeleteEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FightAttr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*W2WAttackReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*W2WAttackResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bound); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vec3F); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*U2GAddEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2UAddEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*U2GDelEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2UDelEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2UUpdateEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*U2GMoveEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2UArea); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_innerpb_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2UCountEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inner_innerpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inner_innerpb_proto_goTypes,
		DependencyIndexes: file_inner_innerpb_proto_depIdxs,
		MessageInfos:      file_inner_innerpb_proto_msgTypes,
	}.Build()
	File_inner_innerpb_proto = out.File
	file_inner_innerpb_proto_rawDesc = nil
	file_inner_innerpb_proto_goTypes = nil
	file_inner_innerpb_proto_depIdxs = nil
}
