package system

const (
	MOVE_SYSTEM       = "MOVE_SYSTEM"
	CROSS_AREA_SYSTEM = "CROSS_AREA_SYSTEM"
	CLEAR_SYSTEM      = "CLEAR_SYSTEM"
	UI_SYSTEM         = "UI_SYSTEM"
	GRID_SYSTEM       = "GRID_SYSTEM"
	CONNECT_SYSTEM    = "CONNECT_SYSTEM"
	FIGHTING_SYSTEM   = "FIGHTING_SYSTEM"
	SYNC_SYSTEM       = "SYNC_SYSTEM"
	SPAWN_SYSTEM      = "SPAWN_SYSTEM"
	DEAD_SYSTEM       = "DEAD_SYSTEM"
)
