// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        (unknown)
// source: gm.proto

package message

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//addItem itemId itemCount //增加某种类型的道具   Arg1:道具类型 Arg2:数量
type GmCommandReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CMD string `protobuf:"bytes,1,opt,name=CMD,json=cMD,proto3" json:"CMD"`
}

func (x *GmCommandReq) Reset() {
	*x = GmCommandReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GmCommandReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GmCommandReq) ProtoMessage() {}

func (x *GmCommandReq) ProtoReflect() protoreflect.Message {
	mi := &file_gm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GmCommandReq.ProtoReflect.Descriptor instead.
func (*GmCommandReq) Descriptor() ([]byte, []int) {
	return file_gm_proto_rawDescGZIP(), []int{0}
}

func (x *GmCommandReq) GetCMD() string {
	if x != nil {
		return x.CMD
	}
	return ""
}

type GmCommandRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result MSG_RESULT `protobuf:"varint,1,opt,name=Result,json=result,proto3,enum=message.MSG_RESULT" json:"Result"`
}

func (x *GmCommandRes) Reset() {
	*x = GmCommandRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GmCommandRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GmCommandRes) ProtoMessage() {}

func (x *GmCommandRes) ProtoReflect() protoreflect.Message {
	mi := &file_gm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GmCommandRes.ProtoReflect.Descriptor instead.
func (*GmCommandRes) Descriptor() ([]byte, []int) {
	return file_gm_proto_rawDescGZIP(), []int{1}
}

func (x *GmCommandRes) GetResult() MSG_RESULT {
	if x != nil {
		return x.Result
	}
	return MSG_RESULT_SUCCESS
}

var File_gm_proto protoreflect.FileDescriptor

var file_gm_proto_rawDesc = []byte{
	0x0a, 0x08, 0x67, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0x0d, 0x6d, 0x73, 0x67, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x20, 0x0a, 0x0c, 0x47, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x4d, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x63, 0x4d, 0x44, 0x22, 0x3b, 0x0a, 0x0c, 0x47, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d,
	0x53, 0x47, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gm_proto_rawDescOnce sync.Once
	file_gm_proto_rawDescData = file_gm_proto_rawDesc
)

func file_gm_proto_rawDescGZIP() []byte {
	file_gm_proto_rawDescOnce.Do(func() {
		file_gm_proto_rawDescData = protoimpl.X.CompressGZIP(file_gm_proto_rawDescData)
	})
	return file_gm_proto_rawDescData
}

var file_gm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gm_proto_goTypes = []interface{}{
	(*GmCommandReq)(nil), // 0: message.GmCommandReq
	(*GmCommandRes)(nil), // 1: message.GmCommandRes
	(MSG_RESULT)(0),      // 2: message.MSG_RESULT
}
var file_gm_proto_depIdxs = []int32{
	2, // 0: message.GmCommandRes.Result:type_name -> message.MSG_RESULT
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gm_proto_init() }
func file_gm_proto_init() {
	if File_gm_proto != nil {
		return
	}
	file_msgtype_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_gm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GmCommandReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GmCommandRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gm_proto_goTypes,
		DependencyIndexes: file_gm_proto_depIdxs,
		MessageInfos:      file_gm_proto_msgTypes,
	}.Build()
	File_gm_proto = out.File
	file_gm_proto_rawDesc = nil
	file_gm_proto_goTypes = nil
	file_gm_proto_depIdxs = nil
}
